### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by zrothberg** [timothyj85/skuvaultpy#1]
Sorry for creating an issue just wanted to know if this worked. I have a project I need to use SKUVault api for.

**Comment by timothyj85** [comment]
I cut this code out of another project and packaged it as a module. You should be able to install it like this:
```pip install --upgrade "git+https://github.com/timothyj85/skuvaultpy.git"```

Pretty much all of the code should work, but you might want to create a fork if the structure isn't quite right for you. I'd be thrilled to see a pull request or feedback also!

**Comment by zrothberg** [comment]
Sorry for the late response I am doing work for a client I can ask if they care about me committing code back, but it appears we have a different use case so this may not be the right solution for me.
